### ISSUE TITLE
NameError: name 'phenny' is not defined

### ISSUE THREAD

**Issue by gstark0** [goavki/phenny#302]
Traceback (most recent call last):
  File "./phenny", line 222, in <module>
    main()
  File "./phenny", line 219, in main
    run(config_module) # @@ thread this
  File "/home/apertium/Desktop/p/phenny/__init__.py", line 64, in run
    t.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/apertium/Desktop/p/phenny/__init__.py", line 50, in run_phenny
    try: connect(config)
  File "/home/apertium/Desktop/p/phenny/__init__.py", line 41, in connect
    p = bot.Phenny(config)
  File "/home/apertium/Desktop/p/phenny/bot.py", line 37, in __init__
    self.setup()
  File "/home/apertium/Desktop/p/phenny/bot.py", line 60, in setup
    tools.setup(self)
  File "/home/apertium/Desktop/p/phenny/tools.py", line 31, in setup
    if hasattr(phenny.config, 'MAX_MSG_LEN'):
NameError: name 'phenny' is not defined

Looks like after last commits, phenny.config should be replaced with self.config

**Comment by ImmortalShox** [comment]
Fixed in #301

**Comment by Androbin** [comment]
@ImmortalShox Can we close this then?

**Comment by Androbin** [comment]
Can we close this issue then?
