### ISSUE TITLE
SASL Attribute Error

### ISSUE THREAD

**Issue by Androbin** [goavki/phenny#363]
```
Traceback (most recent call last):
  File "./phenny", line 162, in <module>
    main()
  File "./phenny", line 159, in main
    run(config_module) # @@ thread this
  File "/media/androbin/Daten/git/phenny/__init__.py", line 74, in run
    t.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/media/androbin/Daten/git/phenny/__init__.py", line 55, in run_phenny
    p.use_sasl = config.sasl
AttributeError: module 'default_config' has no attribute 'sasl'
```
#336 @gstark0 /cc

**Comment by gstark0** [comment]
> Add "sasl = False(or True)" line.

**Comment by Androbin** [comment]
We should `fallback` to the default value.

**Comment by Androbin** [comment]
Right here, next to the other ones:
https://github.com/goavki/phenny/blob/master/phenny#L118

**Comment by gstark0** [comment]
Ye, I will add this later

**Comment by gstark0** [comment]
Can be close.
